### PR TITLE
Like count now displays again

### PR DESCRIPTION
**Pull request by laylar**

### CODE REVIEW

**Review by logicbyjoel — APPROVED** [review]
Good job!

**Review by alexsdeatherage — COMMENTED** [review]
Everything checks out.

**Comment by AngelGDev** [comment]
Looks good to me

**Review by khafrewatkins — COMMENTED** [review]
Looks good

**Review by alexsdeatherage — APPROVED** [review]
Everything is good to be merged to main.

**Review by khafrewatkins — APPROVED** [review]

**Review by AngelGDev — APPROVED** [review]
Approving

**Comment by khafrewatkins** [comment]
Good to go!

**Pull request merged**
